### PR TITLE
Urgent changes for EWL

### LINKED ISSUE #7: ActionTools.Retry shouldn't be extension method
Calling it in that fashion is impractical when you're using it for an anonymous lambda, which both current usages in EWL are doing. And I can't figure out how to even use it when you have an explicit void method with no parameters. This is just a reminder for me to fix this myself.

### LINKED ISSUE #11: Duplicate ToEnum methods
Looks like you meant to move `ToEnum` from `StringTools` to `EnumTools` but forgot to delete it from `StringTools`. It is currently unusable due to this problem.

### LINKED ISSUE #12: NetTools.ExecuteWithResponse needs to be public

### PR DESCRIPTION
**Pull request by william-gross**
Fixes #11 
Fixes #12 
Fixes #7

### CODE REVIEW

**Comment by william-gross** [comment]
Fixes #7. This one isn't urgent but I accidentally included it in this PR by not making a new branch.

**Comment by GregSmalter** [comment]
I think that ExecuteWithResponse needs a way better name if it's to be public. It is not clear what it's for given that it unconditionally uses the HEAD verb.

I probably would have kept the opposite ToEnum - if it's an extension method on a string type, wouldn't we want it in StringTools? That's almost the exact definition of what the xxxTools classes are.

**Comment by william-gross** [comment]
@GregSmalter  I will come up with a better name for `ExecuteWithResponse` and add it to this PR.

I may have kept the opposite `ToEnum` as well, but I'm not the one who moved it to `EnumTools`. That must have been either your or @samrueby , and whoever did it forgot to remove the `StringTools` version. I was just trying to honor the intent of whoever did it.

**Comment by william-gross** [comment]
@GregSmalter I've renamed the ExecuteWithResponse method. Also, for now, I think we should leave ToEnum in EnumTools, both because you or Sam had effectively moved it there already and because it may not be possible/reasonable to always have all extension methods for a given type in the same Tools class. Sometimes you want to group them by some other aspect. For example, in a separate PR I moved BooleanToDecimal and DecimalToBoolean into the same place because they are inverses of each other and are only useful when you're using Oracle. These are stronger sources of cohesion than the type that they operate on, in my opinion.

**Comment by GregSmalter** [comment]
Ok, one last thing. At a minimum, "HEAD' should change to WebRequestMethods.Http.Head. But, what about having a required parameter of type.... ok it would have to be type string so everyone would have to go find WebRequestMethods.Http by themselves, and might not - I was about to ask if we should give its old name back and have it work for all request types. It would probably be better to make one method for each Verb as we need them.

**Comment by william-gross** [comment]
@GregSmalter Fixed.

**Pull request merged**
