### PR TITLE
Added EWL infrastructure

### PR DESCRIPTION
**Pull request by william-gross**
Added EWL infrastructure to enable the Development Utility to produce the NuGet package. Also retargeted to .NET 7.

### CODE REVIEW

**Comment by samrueby** [comment]
I think when this package was first created, it was intended to be decoupled from EWL. I believe our intent was to pull some of the nice utility functions, that could be used anywhere, especially non-EWL projects, without the heavy weight of the rest of the framework, requiring any configuration, or needing to generate any code. I think this PR might be pointing us away from that intent.

**Comment by william-gross** [comment]
@samrueby This PR doesn't change any of that. It's merely a development-time dependency on EWL. The client experience with TEWL is exactly the same.

**Comment by samrueby** [comment]
True... the files being added are still ewl-only-specific things; it feels like a leaky abstraction for TEWL to know about EWL at all.

**Comment by william-gross** [comment]
@samrueby It may feel weird but it’s very practical. It leverages EWL’s ability to produce NuGet packages and automatically upload them to different repositories. I need to be able to publish my own Tewl packages and I did not want to depend on GitHub or Azure CI/CD for this when I already have the EWL infrastructure, which is a better fit for me.

**Comment by samrueby** [comment]
I see. I don't see anyone else using it, though.

I think the key here is " publish my own TEWL packages": I think you can keep these changes in your own fork, and since you need to be able to publish your own TEWL packages (wait, why?), your CI/CD would be pointed to your own repo anyway. You'd still be able to contribute to this repo, and pull in changes.

**Comment by william-gross** [comment]
@samrueby I need my own Tewl packages for the same reason you and Greg need your own EWL packages. Sometimes you need to rapidly make changes and get them into production in a client system.

I am going to build all of my functional Tewl contributions (which you will probably want) on top of this branch, because I don’t want to deal internally with repeatedly merging a cross-cutting branch like this with my other changes.

For the same reason, I recommend that you merge this PR now so that my future contributions are all easier to merge. I am really not seeing the downside; it seems like your only concern is a theoretical objection that future Tewl developers may have. For the current users (you, me, and Greg) there does not seem to be any practical issue. You should still be able to use your current CI/CD setup just fine, without any modifications (except switching the environment to .NET 7 I guess).

**Comment by samrueby** [comment]
Your merges likely would be simple because they would probably never merge-conflict with these files.

I don't agree with this change because there's...7 files to be added that seem to have nothing to do with TEWL that would be confusing for future others and myself (wait, why are these here? Can I touch them? Oh, they're necessary for some other unrelated package? Weird)

I don't like that nuget.exe is included. I haven't seen it included in solutions since NuGet was first introduced.

I don't like that there's a new powershell script to run code generation from EWL against this repo.

I don't like that `<TargetFrameworks>` was removed, probably because it will be generated by the EWL utility, for the same reason I don't like that EWL generates most config. All it takes is wanting one small little change and it's thrown out the window. I personally have at least 4 solutions where I have to undo-changes _every time I generate code_ because my web.config overwritten by EWL is wrong.

I don't see why you can't have these changes in your fork. Again, your ci/cd would already have to point to your repo. Theoretically the repos would differ by this change only. Merge conflicts would be rare only only deal with the csproj files.

**Pull request closed without merging**
